export const HANDLE_FORM_DATA = 'HANDLE_FORM_DATA';
export const HANDLE_COMPANY_OWNER_DATA = 'HANDLE_COMPANY_OWNER_DATA';
export const HANDLE_NEW_PERSON_DATA = 'HANDLE_NEW_PERSON_DATA';
export const TOGGLE_NEW_PERSON_DATA = 'TOGGLE_NEW_PERSON_DATA';
export const HANDLE_COMPANY_GENERAL_INFORMATION = 'HANDLE_COMPANY_GENERAL_INFORMATION';
export const HANDLE_COMPANY_HEADQUARTERS_INFORMATION = 'HANDLE_COMPANY_HEADQUARTERS_INFORMATION';